### ISSUE TITLE
Make Error after Make Clean

### ISSUE THREAD

**Issue by clare7** [ucb-bar/project-template#13]
Hi,

I happened to perform make clean in my /rocket-chip/emulator in order to make new CONFIG.
But right after that, upon new make will give me make error:

make: *** No rule to make target '~/project-template/rocket-chip/emulator/generated-src/rocketchip.RoccExConfig.fir', needed by ~/project-template/rocket-chip/emulator/generated-src/rocketchip.RoccExConfig.v'.  Stop.

Any advice?
Thanks

**Comment by colinschmidt** [comment]
Builds for project-template should be performed in the vsim and verisim directories.

Is the issue that those directories builds are broken afterwards or that building in rocket-chip/emulator is not working?
If its the latter thats just because project-template doesn't support building your example projects inside of rocket-chip.

**Comment by clare7** [comment]
It was the later, so I guess I shall try to do that in vsim and verisim directories.
Thanks
